# Generated by Django 4.2.2 on 2023-06-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_accidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('locacion', models.CharField(max_length=100)),
                ('tipo_avion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Gato',
        ),
    ]
