# Generated by Django 4.2.2 on 2023-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_rename_tipo_de_avion_informe_tipo_avion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='causa_accidente',
            field=models.CharField(default='Sin causa definida', max_length=1000),
        ),
        migrations.AddField(
            model_name='informe',
            name='descripcion_accidente',
            field=models.CharField(default='Sin causa definida', max_length=1000),
        ),
    ]
