# Generated by Django 4.2.2 on 2023-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_delete_accidente_informe_numero_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='numero_caso',
            field=models.IntegerField(),
        ),
    ]
