# Generated by Django 4.2.2 on 2023-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_contacto_telefono_alter_contacto_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
