# Generated by Django 4.2.2 on 2023-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_alter_contacto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
