# Generated by Django 4.2.2 on 2023-08-13 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0016_alter_informe_descripcion_accidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='descripcion_accidente',
            field=ckeditor.fields.RichTextField(max_length=100, null=True),
        ),
    ]
