# Generated by Django 4.2.2 on 2023-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
